
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINAUS CLOSEABBR CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT ENDAUS GARBAGE OPENABBR OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tableskiptag : CONTENT skiptag\n                | CLOSEHREF skiptag\n                | OPENHREF skiptag\n                | handleData : OPENDATA CONTENT CLOSEDATA handleData\n                | OPENDATA   content   OPENHREF content CLOSEHREF CLOSEDATA handleData \n                | OPENHEADER  OPENHREF content CLOSEHREF skiptag OPENHREF content skiptag CLOSEHREF skiptag CLOSEHEADER handleData\n                | OPENDATA OPENSPAN OPENSPAN content CLOSESPAN CLOSESPAN OPENSPAN skiptag OPENSPAN CLOSEDATA handleData \n                | handlerow : OPENROW OPENHEADER OPENABBR content CLOSEABBR CLOSEHEADER handlerow\n                | OPENHEADER OPENABBR content CLOSEABBR CLOSEHEADER handlerow\n                | OPENHEADER content CLOSEHEADER handlerow\n                | CLOSEROW\n                | table : BEGINAUS OPENTABLE handlerow OPENROW handleDataempty : content : CONTENT\n                | empty'
    
_lr_action_items = {'BEGINAUS':([0,],[3,]),'$end':([1,2,9,15,28,34,47,53,60,62,63,64,],[0,-1,-10,-16,-10,-6,-10,-7,-10,-9,-10,-8,]),'OPENTABLE':([3,],[4,]),'OPENROW':([4,5,8,20,27,33,38,39,46,],[6,9,-14,6,-13,6,6,-12,-11,]),'OPENHEADER':([4,6,9,20,28,33,38,47,60,63,],[7,10,17,7,17,7,7,17,17,17,]),'CLOSEROW':([4,20,33,38,],[8,8,8,8,]),'OPENABBR':([7,10,],[11,18,]),'CONTENT':([7,11,13,14,16,18,24,29,30,37,42,43,45,51,54,55,59,],[13,13,-18,-19,21,13,13,13,13,45,45,45,45,13,45,45,45,]),'CLOSEHEADER':([7,12,13,14,26,32,42,43,45,49,50,52,59,61,],[-17,20,-18,-19,33,38,-5,-5,-5,-4,-3,-2,-5,63,]),'OPENDATA':([9,28,47,60,63,],[16,16,16,16,16,]),'CLOSEABBR':([11,13,14,18,19,25,],[-17,-18,-19,-17,26,32,]),'CLOSEHREF':([13,14,24,29,31,35,37,42,43,45,49,50,51,52,54,55,57,59,],[-18,-19,-17,-17,37,40,43,43,43,43,-4,-3,-17,-2,43,43,59,43,]),'CLOSESPAN':([13,14,30,36,41,],[-18,-19,-17,41,48,]),'OPENHREF':([13,14,16,17,21,22,37,42,43,44,45,49,50,51,52,54,55,59,],[-18,-19,-17,24,-18,29,42,42,42,51,42,-4,-3,-17,-2,42,42,42,]),'OPENSPAN':([16,23,42,43,45,48,49,50,52,54,56,],[23,30,-5,-5,-5,54,-4,-3,-2,-5,58,]),'CLOSEDATA':([21,40,58,],[28,47,60,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'handlerow':([4,20,33,38,],[5,27,39,46,]),'content':([7,11,16,18,24,29,30,51,],[12,19,22,25,31,35,36,55,]),'empty':([7,11,16,18,24,29,30,51,],[14,14,14,14,14,14,14,14,]),'handleData':([9,28,47,60,63,],[15,34,53,62,64,]),'skiptag':([37,42,43,45,54,55,59,],[44,49,50,52,56,57,61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','country.py',6),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','country.py',13),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','country.py',14),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','country.py',15),
  ('skiptag -> <empty>','skiptag',0,'p_skiptag','country.py',16),
  ('handleData -> OPENDATA CONTENT CLOSEDATA handleData','handleData',4,'p_handleData','country.py',22),
  ('handleData -> OPENDATA content OPENHREF content CLOSEHREF CLOSEDATA handleData','handleData',7,'p_handleData','country.py',23),
  ('handleData -> OPENHEADER OPENHREF content CLOSEHREF skiptag OPENHREF content skiptag CLOSEHREF skiptag CLOSEHEADER handleData','handleData',12,'p_handleData','country.py',24),
  ('handleData -> OPENDATA OPENSPAN OPENSPAN content CLOSESPAN CLOSESPAN OPENSPAN skiptag OPENSPAN CLOSEDATA handleData','handleData',11,'p_handleData','country.py',25),
  ('handleData -> <empty>','handleData',0,'p_handleData','country.py',26),
  ('handlerow -> OPENROW OPENHEADER OPENABBR content CLOSEABBR CLOSEHEADER handlerow','handlerow',7,'p_handlerow','country.py',30),
  ('handlerow -> OPENHEADER OPENABBR content CLOSEABBR CLOSEHEADER handlerow','handlerow',6,'p_handlerow','country.py',31),
  ('handlerow -> OPENHEADER content CLOSEHEADER handlerow','handlerow',4,'p_handlerow','country.py',32),
  ('handlerow -> CLOSEROW','handlerow',1,'p_handlerow','country.py',33),
  ('handlerow -> <empty>','handlerow',0,'p_handlerow','country.py',34),
  ('table -> BEGINAUS OPENTABLE handlerow OPENROW handleData','table',5,'p_table','country.py',38),
  ('empty -> <empty>','empty',0,'p_empty','country.py',43),
  ('content -> CONTENT','content',1,'p_content','country.py',48),
  ('content -> empty','content',1,'p_content','country.py',49),
]
